version: '3'

services:
  nextdom-v2:
    build:
      context: install
    image: nextdom-v2
    container_name: nextdom-v2
    restart: always
    ports:
    - 1880:1880/tcp
    - 1883:1883/tcp
    networks: 
    - nextdom
    volumes:
    - ./data/mqtt:/var/lib/mosquitto
    - ./data/nodered:/data
  nextdom-db:
    image: postgres:latest
    container_name: nextdom-db
    hostname: nextdom-db
    restart: always
    networks:
    - nextdom
    ports:
    #- 3306:3306
    - 5432:5432
    volumes:
    - ./data/db:/var/lib/postgresql
    - ./install/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DATABASE=nextdom
    #- MYSQL_ROOT_PASSWORD=admin
    #- MYSQL_DATABASE=nextdom
    #- MYSQL_PASSWORD=nextdom
    #- MYSQL_USER=nextdom
  nextdom-api:
    build:
      context: rest
    image: nextdom-api
    container_name: nextdom-api
    restart: always
    ports:
    - 3000:3000
    networks:
    - nextdom
  adminer:
    image: adminer:latest
    restart: always
    networks:
    - nextdom
    ports: 
    - 9080:8080


networks:
  nextdom:
    driver: bridge
    name: nextdom
