openapi: 3.0.0
info:
  title: nextdom-rest
  version: 0.0.1
  description: nextdom-rest-api
  contact:
    name: Sylvaner
    email: sylvain.dangin@gmail.com
paths:
    get:
      x-controller-name: LightController
      x-operation-name: findById
      tags:
      - LightController
      responses:
        '200':
          description: Light model instance
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Light"
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      operationId: LightController.findById
servers:
- url: http://localhost:3000
components:
  schemas:
    Light:
      title: Light
      type: object
      properties:
        id:
          type: string
        data:
          type: object
      required:
      - id
      - data
      additionalProperties: false
